Controllers/Admin/AuthorController.cs
using Microsoft.AspNetCore.Mvc;

namespace BookShopProject.Controllers.Admin
{
    public class AuthorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/BookController.cs
using BookShopProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookShopProject.Controllers
{
    public class BookController : Controller //use for Book, Author & Type
    {

        [HttpGet]
        public IActionResult IndexPage()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Book book)
        {

            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return RedirectToAction("Create");
        }

        [HttpGet]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Book book)
        {
            return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            return View();
        }



    }
}

Controllers/SessionController.cs
using Microsoft.AspNetCore.Mvc;

namespace BookShopProject.Controllers
{
  public class SessionController : Controller
  {
    public IActionResult Index()
    {
      return View();
    }

    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Create(string name, string password)
    {
      return RedirectToAction();
    }



  }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookShopProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/session.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/header.css" asp-append-version="true" />
</head>
<body>
    <div class="body">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookShopProject - <a asp-area="" asp-controller="Session" asp-action="Create">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookShopProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/session.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboard/header.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboard/sidebar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboard/dashboard.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/index-body/index.css" asp-append-version="true" />
</head>
<body class="body">
    <div class="left-section">
        <nav class="sidebar-navigation">
            <div class="close-sidebar-navigation">
                <div class="sidebar-title">Bookshop</div>
            </div>
            <ul class="sidebar-navigation-list">
                <li class="sidebar-link">
                    <a asp-controller="Book" asp-action="IndexPage">
                        <img class="sidebar-link-icon" src="/icons/dashboard_64px.png" />
                        Dashboard
                    </a>
                    
                </li>
                <li class="sidebar-link">
                    <img class="sidebar-link-icon" src="/icons/fingerprint_64px.png" />
                    Information
                </li>
                <li class="sidebar-link">
                    <img class="sidebar-link-icon" src="/icons/product_64px.png" />
                    Catalog
                </li>
                <li class="subsidebar-link">
                    <a asp-controller="Book" asp-action="IndexPage">Book List</a>
                </li>
                <li class="subsidebar-link">
                    <a asp-controller="Category" asp-action="Index">Category List</a>
                </li>
                <li class="subsidebar-link">
                    <a asp-controller="Author" asp-action="Index">Author List</a>
                </li>
                <li class="sidebar-link">
                    <img class="sidebar-link-icon" src="/icons/Mine Cart_128px.png" />
                    Order
                </li>
                <li class="sidebar-link">
                    <img class="sidebar-link-icon" src="/icons/search_client_64px.png" />
                    Customer
                </li>
                <li class="sidebar-link">
                    <img class="sidebar-link-icon" src="/icons/staff_64px.png" />
                    Staff
                </li>
                <li class="sidebar-link">
                    <img class="sidebar-link-icon" src="/icons/logout_rounded_down_64px.png" />
                    Log out
                </li>
            </ul>
        </nav>
    </div>
    <div class="right-section">
        <header class="header">
            <div class="left-header-section">
                <input class="search-header-bar" placeholder="Search" type="text" />
                <img class="search-header-icon" src="/icons/search_100px.png" />
            </div>
            <div class="right-header-section">
                <img class="avatar-header" src="/images/75150646.jpg" />
                <div class="user-header-info">
                    <div class="user-header-name">Name</div>
                    <div class="user-header-email">name@gmail.com</div>
                </div>
            </div>
        </header>
        <div class="body">
            <main class="main-body" role="main">
                @RenderBody()
            </main>
        </div>
        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2023 - BookShopProject - <a asp-area="" asp-controller="Dashboard" asp-action="Index">Home</a>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookShopProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/header.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/partial/book.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/book/detail.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookShopProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="header">
        <div class="left-section">
            <img class="logo" src="~/images/fahasa_logo.png" />
        </div>
        <div class="middle-section">
            <button class="category-button">
                <img class="category-icon" src="~/icons/menu_rounded_64px.png" />
                <ul class="category-dropdown-menu">
                    <li class="dropdown-item"><a>Type1</a></li>
                    <li class="dropdown-item"><a>Type2</a></li>
                    <li class="dropdown-item"><a>Type3</a></li>
                    <li class="dropdown-item"><a>Type4</a></li>
                    <li class="dropdown-item"><a>Type5</a></li>
                    <li class="dropdown-item"><a>Type6</a></li>
                    <!-- this is where define type-->
                </ul>
            </button>
            <input class="search-bar" placeholder="Search" type="text"/>
            <div class="search-button">
                <img class="search-icon" src="~/icons/ico_search_white.svg"/>
            </div>
        </div>
        <div class="right-section">
            <button class="cart-button">
                <img class="cart-icon" src="~/icons/ico_cart_gray.svg"/>
            </button>
            <button class="account-button">
                <img class="account-icon" src="~/icons/ico_account_gray.svg" />
            </button>
         </div>
    </header>
    <div class="body">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookShopProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>